tutorials=Tutorials
help=help

concepts=Fundamental concepts <span class="text-secondary small">(2:30 min)</span>
exhibitions-tutorials=How to create and edit Exhibitions <span class="text-secondary small">(53 secs)</span>	



create-audio-guide= Audio Guides <span class="text-secondary small">(2:22 min)</span>
link-create-audio-guide=ttps://youtu.be/qREFkyV7IS0


use-audio-studio=Audio Studio <span class="text-secondary small">(2 min)</span>
link-use-audio-studio=https://youtu.be/9fKGECJAftk?si=DYihh345IjiR08Y5

create-public-portal=Visitor guide <span class="text-secondary small">(53 segs)</span>
link-create-public-portal=https://youtube.com/shorts/usnc4ZzhrIk?feature=share

 
 

link-concepts=https://youtu.be/pmGKYHwgCi8?si=NGAHGp8qQmExedX8
link-exhibitions=https://youtu.be/OyXFbTFCe4k?si=Qu-_hJ53Y0ucKh7a
link-audioguides-tutorials=https://youtu.be/qREFkyV7IS0?si=x-n9wDKUzJHjW4v6



publish-public-portal=Publish the Visitor guide and QRs <span class="text-secondary small">(58 segs)</span>
link-publish-public-portal=https://youtu.be/fYCAdn9naJA


manuals=Manuals
manual-concepts=Concepts 
setup-site=Setup site

manual-exhibitions=Exhibitions 
manual-audio-guides=Audio guides

manual-publish-public-portal=Visitor guide 
faqs=Preguntas frequentes
reports=Reports
content-management=Content management