welcome-dellemuse=Welcome to Dellemuse
learn-concepts=Learn the fundamental concepts in 2 minutes.

close-forever=Close and do not show again
more-tutorials=More tutorials
audio-studio=Audio Studio
audio-guides= Cómo crear y editar Audio Guías

create-exhibitions= Cómo crear y editar Exhibiciones
public-portal=Visitor guide and QRs

publish-public-portal=Publish the Visitor guide and the site's QRs

manuals=Manuals
concepts=Concepts
site-setup=Site setup
exhibitions=Exhibitions
audio-guides=Audio guides
security=Security
