username=Username
new-password=New password
email=Email
notice=Please enter new password for <b>{0}</b> (  {1}  )

password-reset-success=Password reset successful. You can now sign in with your new password.
