qrcode=QR Code
noqrcode=No QR code available
generate-qrcode=generate QR code
generate-pdf=generate pdf
audio-number-png=Audio Number
generate-audio-number-png=generate audio number png

pdf=PDF with QR code and Audio Number
