
exhibition-info=Information
artworks=Artworks
exhibition-guides=Audio guides (all)
exhibition-guides-title=Audio guides 

items=Artworks in Exhibition
guides=Guides
audio=Audio

art-exhibition={0} (Art exhibition)
exhibition-sections=Sections
exhibition-qrcode=QR Code




information=Information
information-record=Information ({0})


exhibition-info-record=Exhibition info ({0})
meta=State 
sections=Sections


art-exhibition-title=Art Exhibition
items-title=Artworks and Objects
