sites=Sites
candidates=Candidates
resources=Resources
security=Security
recent-signins=Recent Sign-ins


today=Today
yesterday=Yesterday
last-7-days=Last 7 days
last-30-days=Last 30 days
last-12-months=Last 12 months
all=All



