title=Reports
date-range=Date range
users=Users
site-visits=Site users
exhibition-guides-users=User sessions by audio guide

today=Today
yesterday=Yesterday
last-7-days=Last 7 days
last-30-days=Last 30 days
last-12-months=Last 12 months
all=All
site=Site
site-users=Site users
total=Total
site-users-by-language=User sessions by language
