record-language=Record Language

metainfo=State  
translatemode=Machine translation (texts)
masterlanguage=Master language

audiomode=Audio generated automatically 


notice=Your user does not have permission to edit <b>{0}</b>.  
