name=Name
subtitle=Subtitle
info=Info
info-accessible=Accessible Info
audio-accessible=Accessible Audio
translate-information=Information ({0})
translate-button-text=Translate from {0}
open-audio-studio=Open Audio Studio ({0})
