general-info=Information
personName= Name
personLastname=Last name

status=Status
email=Email
phone=Phone
institutionName=Institution name 
institutionAddress=Institution address

comments=Comments
references=References
candidate=Candidate
submit=Send

onboarding=Sign up

submitted-ok=The form was submitted successfully.<br/> We will review the information and contact you once the account is enabled, normally within 24 hrs.
mandatory-fields-not-filled=The fields Person last name, Email,   Institution name are mandatory. <br/> Please fill them in before submitting the form.

password=Password
