general-info=Information
personName= Name <span class="text-secondary" style="font-weight:normal;">( your name )</span>
personLastname=Last name <span class="text-secondary" style="font-weight:normal;">( your last name )</span>

status=Status
email=Email <span class="text-secondary" style="font-weight:normal;">( must be your vaild email address )</span>
phone=Phone <span class="text-secondary" style="font-weight:normal;">( optional )</span>
institutionName=Institution name <span class="text-secondary" style="font-weight:normal;">( the institution you are registering )</span>
institutionAddress=Institution address

comments=Comments
references=References
candidate=Candidate
submit=Send

onboarding=Sign up

submitted-ok=The form was submitted successfully.<br/> We will send email with the credentials for start using the service, normally within 24 hrs.
mandatory-fields-not-filled=These fields are mandatory: <br/>  <b>Person Last name</b><br/>   <b>Password</b><br/>   <b>Email</b><br/>   <b>Institution name</b> 

password=Password <span class="text-secondary" style="font-weight:normal;">( enter a new password for your account )</span>

