institutionApprox=Institution candidate

institutionChoice=Select institution
create-institution=Create 


selected=Selected
institutionCreated=Institution created

none=none


selected-will-be-added-to-candidate=The selected institution will be added to the candidate on 'Save'
create-institution-text=If the institution does not exist, you can create a new one here. The institution and the site will be created with the values from the candidate form.
