general-info=Information
personName=Contact name
personLastname=Contact last name

status=Status
email=Email
phone=Phone
institutionName=Institution 
institutionAddress=Institution address

comments=Comments
internalcomments=Internal comments
references=References
candidate=Candidate
submit=Send
emailValidated=Email validated
internal-use=Internal use
candidate=Candidate

validationEmailSent=Validation email date

institutionChoice=Select Institution

internal-use=Internal use

create-institution=Create institution
user=User
create-user=Create user
institutionApprox=Instituion candidate

userInfo=User info
sendEmail=Send Welcome email
