general-info=Information
personName=Contact name
personLastname=Contact last name

status=Status
email=Email
phone=Phone
institutionName=Institution 
institutionAddress=Institution address

comments=Comments
internalcomments=Internal comments
references=References
candidate=Candidate
submit=Send
emailValidated=Email validated
internal-use=Internal use
candidate=Candidate