qrcode=QR Code
noqrcode=No QR code available
generate-qr-code=Generate QR code
generate-pdf=generate PDF
audio-number-png=Audio Number
generate-audio-number-png=generate audio number png
pdf=PDF with QR code and Audio Number