title=Reports
date-range=Date Range
users=Users
total-users=Total Users
today=Today
yesterday=Yesterday
last-7-days=Last 7 Days
last-30-days=Last 30 Days
last-12-months=Last 12 Months
all=All
languages=Languages
other-guides=Other Guides from same Artwork